### ISSUE TITLE
cache API responses on server side

### ISSUE THREAD

**Issue by bibliocoll** [bibliocoll/JournalTouch#21]
currently, responses from JournalTOC or CrossRef are requested, consumed, delivered to the client and promptly forgotten. thats horribad and needs to change.

libmon-php uses PEAR::Cache_Lite, this should work for JT as well.

a more thorough solution would be some kind of database that is maintained by a background process / cron job, but i'm not sure about increasing the installation footprint, given our target audience.

**Comment by tzeumer** [comment]
The most simple way might be to cache to files like issn-lastupdate.txt - then something like 

`$toc = (file_get_contents("$issn_$update_date.txt") ? file_get_contents("$issn_$update_date.txt" : update_toc();`

And update_toc should delete any issn_*.txt files before creating a new one.

I thought about a sqllite-db but a) it requires the php module (but it usually is not activated by default) and b) at the current point it appears like overkill - there is nearly nothing that we don't want to load on first access. Or maybe we would want to load less, but it would break filtering etc. Hmm... :)

**Comment by bibliocoll** [comment]
i'll branch and drop in Cache_Lite tomorrow, it has proven to be simple and effective for libmon-php. might make sense to additionally cache on the client side as well, but thats for a second iteration.

also, i guess i should either keep this in a branch for a while, or find and document a good way to invalidate the caches. a cache cascade tends to mess with F5-style development ;)

**Comment by krugar** [comment]
[branch server_side_cache] (https://github.com/bibliocoll/JournalTouch/tree/server_side_cache) introduces this feature, but adds a requirement for [PEAR::Cache_Lite] (http://pear.php.net/manual/en/package.caching.cache-lite.intro.php). speedup on subsequent lookups is as expected, eg: "wheee!" :wink:

not entirely sure if and when this should be merged into master, since it might break some installations. cf #29
