### ISSUE TITLE
sort journal list by date of last publication

### ISSUE THREAD

**Issue by bibliocoll** [bibliocoll/JournalTouch#23]
JT is supposed to make new journal releases visible, this end is not served well by the alphabetical list being the default and only view.

maintain a list of "last-updated"-dates for all journals and make the default list sorted with most recent publications displayed first.

**Comment by tzeumer** [comment]
I had the same thought, albeit maybe a step further. It'd be cool to link to filter and tag item like jounaltouch.net/filterx. This would include the "new issues" filter. The only "drawback" is, that titles always have to be loaded to keep it "javascript-dynamic".

The very easiest way might be a mod rewrite. Just match any path item against the entries in tag/filter. If there is a match, apply the filter. Subsequent clicks on tag/filters should manipulate the url via history.pushState(). Thus it would look like real browsing while only existing filters are applied.

This might be cool for course reserves too (which would be nothing else than filters).

**Comment by krugar** [comment]
do this after the non-css work on #26 is done

**Comment by tzeumer** [comment]
This is an very ugly 5 minute hack: https://github.com/tzeumer/JournalTouch/tree/pr-sort_by_date

Basically it is working (I think) plus this script offers quite a lot more nice options to sort stuff...

Still, we have to hide the alphabet. Instead it would be really cool to have the last 12 month as jumping points.

Ok, this was just a quickie befoe bedtime ;)

**Comment by tzeumer** [comment]
Hmm, this ticket isn't as simple as it looks. More and more I come to the conclusion, that the alphabetic list is nearly pointless, especially since the filtering is available. The only reason to keep it: I like it (so, no good reason at all). Currently the orbit view is a hybrid of both. While it looks nice, it would be _just_ another view if everything is sorted by date already.

However, a sorting by date makes the limits of JT much more obvious. Those limits are
 1. Some journals return future publishing dates (e.g. IEEE). But timeago always shows "ago" (this might easily be solved by showing the full date - even though future dates remain hard to explan :))
 2. For some journals no toc can be fetched (thus no date for a recent issue is available[1]). This can not easily be resolved.<br />The easiest way would be to remove them from JT. This might work if it mainly concerns print (only) editions, you use JT only inhouse (not available via internet) and next to the JT display you have a shelf with those journals. It's the easiest, but also the worst option in my opinion.<br />The second easiest might be to include a publishing frequency in input.csv, so the last published edition can be calculated (I think this might work for a lot journals being in question). But this adds lots of manual editing and makes it harder to convince decision makers to consider using JT.<br />I wonder about a third option like some open data source to get these information...
The second point makes switching to sorting by date a very major decision in JT's development, I think.

However the above points are solved, additional questions arise
 1. input.csv should sorted by date by default (sounds easy as long people editing the file remember this or know how to use CTRL+F)
 2. The alphabet links and the letter as indicator for the current position have to be removed. Probably a nice alternative would be the last 4 weeks + the last 12 months as jumping points.
 3. If alphabetical sorting is to stay as an option, the sorting has to be done and the alphabet links have to be shown on switch.

Maybe there are more issued related to such a change...

> Footnote<br/>[1] In my current dataset this is mainly the case for german journals or non-scientific journals (e.g. C't or Test). Anyway, kicking them out because they are hard to handle, isn't a good option in my opinion. I think some of these journals are even especially interesting for such a presentation.

**Comment by krugar** [comment]
tinysort is remarkably fast :)

**Comment by tzeumer** [comment]
*Psst* if it is available, it might be. It's not in the commit ;)

Also, for me it breaks becauseyou you added __DIR__'s in class.ListJournals.php. I really wonder, why it would ever work for you, since the basepath is set in bootstrap.php :-?

**Comment by krugar** [comment]
done, i hope :)
