### ISSUE TITLE
update README.md for 0.3

### ISSUE THREAD

**Issue by krugar** [bibliocoll/JournalTouch#41]
@pafru and me are going to make this pretty before we push it out the door

**Comment by tzeumer** [comment]
Offtopic: Just curious, how about using this: https://gitter.im.This is a nice way to keep in touch since github doesn't offer anything itself.

**Comment by krugar** [comment]
not sure if we really need to? we all have our email adresses in the source & mine also works for xmpp :)

**Comment by tzeumer** [comment]
Spoke with someone about what's necessary for JT and since then I think that the most essential information should be part of the readme.md here. The wiki is fine, yet it's better suited for in detail information. 

I think the readme should point out these point
1. Requirements (Apache, PHP, a free JournalToc account)
2. A list of ISSNs
3. A way to get the journals cover 

Regarding the 3rd point I just got an interesting answer from JournalToc - the premium account offers covers via api. https://twitter.com/JournalTOCs/status/659370134323204097

Also there is http://www.stmcovers.com/. Even though the site itself looks suspicious (no infos about the host at all) the domain is registered with Elsevier. Well, it has not to be true (I think it's not too hard to register a domain with wrong credentials), yet anyone can decide for himself. 

So we can point to two options for getting covers... :)

**Comment by krugar** [comment]
we will get the cover functionality unlocked in our journaltocs premium account sometime in april and i will make a point release with an updated journaltocs cover provider when i have access to the api.
