### ISSUE TITLE
folder from TAR.GZ file uses different name then TAR.GZ archive

### ISSUE THREAD

**Issue by realsobek** [bibliocoll/JournalTouch#69]
This might be not related to JournalTouch, but GitHub in general.

The URL:
`https://github.com/bibliocoll/JournalTouch/tarball/master`
or
`https://codeload.github.com/bibliocoll/JournalTouch/legacy.tar.gz/master`
downloads the file:
`bibliocoll-JournalTouch-0.4.1-1-g869729f.tar.gz`

If I extract it a folder is created with the name:
`bibliocoll-JournalTouch-869729f`

I wonder:
* why is the 'g' missing at the start of the hash?
* why is the version (0.4.1-1) not in name of extracted folder?

From my point of view the name of the created folder should match the name of the archive, minus the extension.

**Comment by krugar** [comment]
the release packaging is indeed done by github. i agree with what you've written and i'll re-read the github documentation before the next point release, but i'm afraid i won't be able to change anything on that front. 

if you are doubtful about the contents of the release tarball, i would suggest cloning the repository and checking out the master branch (or, even more specific, the newest tagged commit on the master branch).

i'm closing this issue since it is very likely not specific to this project.

**Comment by realsobek** [comment]
I am not doubting the content of the release tarball :)
the different name requires more commands for automated installation, that is why I reported this
