### ISSUE TITLE
PHP Notice: Undefined property: stdClass::$dbhost in admin/settings.php on line 853

### ISSUE THREAD

**Issue by realsobek** [bibliocoll/JournalTouch#75]
I am using JournalTouch 0.4.1 on CentOS 7 x86_64 with centos-release-scl package and packages:
php55 
php55-php
php55-php-mbstring

After installation of JournalTouch, everytime I visit the page:
http://journaltouch/admin/settings.php

In the log file:
`tail -f /var/log/httpd24/error_log`
you can see the output:
`[Wed Apr 13 09:09:02.618439 2016] [:error] [pid 888] [client 141.14.232.200:34152] PHP Notice:  Undefined property: stdClass::$dbhost in /opt/rh/httpd24/root/var/www/html/bibliocoll-JournalTouch-869729f/admin/settings.php on line 853, referer: http://journaltouch/admin/index.php`

There does not seem to be any problem as far as I can see.
Do I have to take action to solve the 'PHP Notice' message?

**Comment by krugar** [comment]
@tzeumer this is related to your todo-comment in [admin/settings.php#L9](https://github.com/bibliocoll/JournalTouch/blob/master/admin/settings.php#L9), if you've made up your mind on how you want to handle this, now would be a good time to let me know. i might come up with my own solution otherwise (dun Dun DUN!) :wink:

**Comment by tzeumer** [comment]
Oh, fixed it already (at least I think so) and I think it is already part of the development branch here. In my repository it was this issue: https://github.com/tzeumer/JournalTouch/issues/6 - it's fixed by this commit: https://github.com/tzeumer/JournalTouch/commit/5f1bc4fdb88230f486a6a0d138f88ab696a19f1c

I'm "notice free" so far... :)

**Comment by krugar** [comment]
@tzeumer: i'd like to include your changes into a 0.4.2 point release instead of ratcheting up to 0.5, as these are mainly bugfixes. would it break anything on your end if i renamed your current [upgrade_0.5.php](https://github.com/tzeumer/JournalTouch/blob/develop_ver-0.5.0/admin/upgrade/versions/upgrade_0.5.php) to upgrade_0.4.2.php after merging it into `develop`?

**Comment by tzeumer** [comment]
It's just a different number, so it should not. Think of changing it in bootstrap.php, too. 

On the other hand, maybe just wait for the new session handling code an then make it 0.5? :)

**Comment by krugar** [comment]
i'd like to publish 0.4.2 this week so the current stable is actually usable, new features -> 0.5

**Comment by tzeumer** [comment]
This week - ok, that is not much time. Bit off topic (don't find the old topic): I think the spellchecking thingy did too much. "Autor" (german) was fixed to "author" - maybe there was more. Forgot to check it and no time at the moment.

**Comment by realsobek** [comment]
I could not reproduce with 0.4.2, hence clicking 'close and comment'
