### ISSUE TITLE
change CHM doc format to more accessible format

### ISSUE THREAD

**Issue by bibliocoll** [bibliocoll/JournalTouch#9]
doc/jt-documentation.chm (Pull request merge)

**Comment by krugar** [comment]
i kinda like the github wiki for non-apidoc stuff.   
not sure how much generated-from-source documentation i want to keep under version control...

**Comment by tzeumer** [comment]
This is partly an auto generated code documentation that uses the DocBlocks-tags (see: http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.pkg.html). 

This is (mostly) a different purpose from documenting api's. It helps others to understand the code, find references in it and stuff like that. So, concerning exactly this ticket, I think the best option would be to use another "documentation" branch for this. Or kick it alltogether. Everyone could generate the docs themselves from the code. So offering it for download is just a nice service for anyone who doesn't know how to do it. Anyway, someone would have to generate if from time to time (I guess this is, why you don't find it that often :D)

And as I said, chm was only chosen because it was the best "one file only output format" (_if_ you can use chm, it is a great format for such stuff). Doxygen and related tools output a lot more formats, maybe even epub in between :D
